// Generated by CoffeeScript 1.10.0
(function() {
  var JsCoreDataRouter, async, bodyParser, cors, express, expressErrorResponse, expressResponseRange;

  express = require('express');

  cors = require('cors');

  async = require('async');

  bodyParser = require('body-parser');

  expressErrorResponse = require('express-response-error');

  expressResponseRange = require('express-response-range');

  JsCoreDataRouter = (function() {
    function JsCoreDataRouter(database) {
      this.database = database;
    }

    JsCoreDataRouter.prototype._defaultRouter = function(entityName, options) {
      var router;
      if (options == null) {
        options = {};
      }
      router = express.Router();
      router.use(require('./lib/_')(this.database, entityName, options));
      return router;
    };

    JsCoreDataRouter.prototype.all = function(entityName, options) {
      var router;
      if (options == null) {
        options = {};
      }
      router = this._defaultRouter(entityName, options);
      router.use(require('./lib/all')(entityName, options));
      return router;
    };

    JsCoreDataRouter.prototype.get = function(entityName, options) {
      var router;
      if (options == null) {
        options = {};
      }
      router = this._defaultRouter(entityName, options);
      router.use(require('./lib/get')(entityName, options));
      return router;
    };

    JsCoreDataRouter.prototype.post = function(entityName, options) {
      var router;
      if (options == null) {
        options = {};
      }
      router = this._defaultRouter(entityName, options);
      router.use(require('./lib/post')(entityName, options));
      return router;
    };

    JsCoreDataRouter.prototype.put = function(entityName, options) {
      var router;
      if (options == null) {
        options = {};
      }
      router = this._defaultRouter(entityName, options);
      router.use(require('./lib/put')(entityName, options));
      return router;
    };

    JsCoreDataRouter.prototype["delete"] = function(entityName, options) {
      var router;
      if (options == null) {
        options = {};
      }
      router = this._defaultRouter(entityName, options);
      router.use(require('./lib/delete')(entityName, options));
      return router;
    };

    return JsCoreDataRouter;

  })();

  module.exports = JsCoreDataRouter;

}).call(this);
