// Generated by CoffeeScript 1.10.0
(function() {
  var express;

  express = require('express');

  module.exports = function(entityName, options) {
    var router;
    if (options == null) {
      options = {};
    }
    router = express.Router();
    router.use(require('./get')(entityName, options));
    router.use(require('./post')(entityName, options));
    router.use(require('./put')(entityName, options));
    router.use(require('./delete')(entityName, options));
    return router;
  };

}).call(this);
