// Generated by CoffeeScript 1.10.0
(function() {
  var express;

  express = require('express');

  module.exports = function(entityName, options) {
    var router;
    if (options == null) {
      options = {};
    }
    router = express.Router();
    router["delete"]('/:id', function(req, res, next) {
      return req.context.getObjectWithId(entityName, req.params.id).then(function(item) {
        if (!item) {
          res.notFound(entityName + ' with id ' + req.params.id + ' not found');
        }
        req.context.deleteObject(item);
        return req.context.save();
      }).then(function() {
        return res.status(204).end();
      })["catch"](next);
    });
    return router;
  };

}).call(this);
