// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, express;

  express = require('express');

  Promise = require('bluebird');

  module.exports = function(entityName, options) {
    var getter, router, setterFunction;
    if (options == null) {
      options = {};
    }
    router = express.Router();
    setterFunction = options.setValues || function(data) {
      data.item.setValues(data.req.body);
      return Promise.resolve();
    };
    getter = options.getValues || function(data) {
      return Promise.resolve(data.item.getValues());
    };
    router.post('/', function(req, res, next) {
      req.item = req.context.create(entityName);
      return setterFunction({
        req: req,
        item: req.item
      }).then(function() {
        return next();
      })["catch"](next);
    });
    router.post('/', function(req, res, next) {
      return req.context.save().then(function() {
        res.status(201);
        return getter({
          req: req,
          item: req.item
        }).then(function(data) {
          return res.send(data);
        });
      })["catch"](next);
    });
    return router;
  };

}).call(this);
