// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, express;

  express = require('express');

  Promise = require('bluebird');

  module.exports = function(entityName, options) {
    var getter, router, setterFunction;
    if (options == null) {
      options = {};
    }
    router = express.Router();
    setterFunction = options.setValues || function(data) {
      console.log(data.req.body, '!!!');
      data.item.setValues(data.req.body);
      return Promise.resolve();
    };
    getter = options.getValues || function(data) {
      return Promise.resolve(data.item.getValues());
    };
    router.put('/:id', function(req, res, next) {
      console.log('!!!!');
      return req.context.getObjectWithId(entityName, req.params.id).then(function(item) {
        if (!item) {
          return res.notFound(entityName + ' with id ' + req.params.id + ' not found');
        }
        req.item = item;
        return setterFunction({
          req: req,
          item: item
        });
      }).then(function() {
        return next();
      })["catch"](next);
    });
    router.put('/:id', function(req, res, next) {
      return req.context.save().then(function() {
        return getter({
          req: req,
          item: req.item
        }).then(function(data) {
          return res.send(data);
        });
      })["catch"](next);
    });
    return router;
  };

}).call(this);
